### PR TITLE
v9 fixes

### PR DESCRIPTION
**Pull request by kaystrobach**
@astehlik merging your changes back to master

### CODE REVIEW

**Comment by astehlik** [comment]
@kaystrobach Thanks for taking care. 

Please let me know if I can assist you or improve things.

**Comment by kaystrobach** [comment]
Would you mind fixing the 2 issues codefactor claims, the other code looks good so far.

**Comment by astehlik** [comment]
Hi @kaystrobach 

Sorry for my late reply.

If fixed the issues in the `notracker.html`.

Can you exclude the `MatomoTracker.php` file from the CodeFactor checks? This is basically a third party library and should not be modified IMO. At some point we might event consider loading it via Composer which finally seems to be possible :)

https://packagist.org/packages/matomo/matomo-php-tracker

**Comment by kaystrobach** [comment]
yes, we can move to composer, agree on that, just need to take care of TER here. which means the uploader also has to create a non composer version before

**Comment by kaystrobach** [comment]
Thank you for your PR

**Pull request merged**
