### PR TITLE
Several enhancements and bug fixes

### PR DESCRIPTION
**Pull request by astehlik**
The composer.json commit is not part of this pull request.

### CODE REVIEW

**Comment by km-digitalpatrioten** [comment]
Hi,

please merge this as soon as you find time. The async support is very useful! Tahnks @astehlik for your effort! For the meantime i use a fork of @astehlik 's branch.

**Comment by kaystrobach** [comment]
Thanks a lot
@astehlik sry for the late response could you please do some CGL cleanup:

e.g.

```
 function __construct($idSite, $apiUrl = '')
 {
```

should be 

```
 function __construct($idSite, $apiUrl = '') {
```

Then i can merge it - thank you for your great work!

**Comment by astehlik** [comment]
I guess you are talking about the Tx_Piwik_PiwikApi_PiwikTracker from the 021e1d71431a169f7f87f4946928611bb41ca65f commit.

Please note that this file is provided by Piwik (http://piwik.org/docs/tracking-api/#piwik-tracking-api-advanced-users). I only changed the class name to fit into the TYPO3 context. The rest is the original class from Piwik. I would not do any CGL cleanup there to make future updates easier.

If there are other files, where code cleanup is needed, please let me know :)

Cheers,
Alex

**Comment by kaystrobach** [comment]
ok, will merge

**Comment by kaystrobach** [comment]
just drafted a new release to TER, thanks a lot!
will be 3.1.0

**Comment by kaystrobach** [comment]
http://typo3.org/extensions/repository/view/piwik

**Comment by astehlik** [comment]
That's great.  Thank you very much :)

**Comment by kaystrobach** [comment]
Thank you! :+1:

**Comment by km-digitalpatrioten** [comment]
Thanks guys!

**Pull request merged**
